name: Main CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    uses: ./.github/workflows/android.yml

  ios:
    uses: ./.github/workflows/ios.yml
